### ISSUE TITLE
Tag release of 2.2-3

### ISSUE THREAD

**Issue by zkamvar** [mrc-ide/EpiEstim#100]
Sorry I've been absent on this. It would be good to tag the new version as it was released to CRAN. I think tagging the most recent commit with 2.2-3 would be sufficient.

**Comment by richfitz** [comment]
Done, thanks @zkamvar

**Comment by richfitz** [comment]
(I will leave it to others to prettify the release with NEWS etc if they wany)

**Comment by jstockwin** [comment]
I've added the content of `NEWS.md` to the release.
