### ISSUE TITLE
DOI

### ISSUE THREAD

**Issue by t-pollington** [mrc-ide/EpiEstim#112]
Dear MRC,

I was going to cite your package at this repo (I'm also citing your methodological papers elsewhere) and was wondering if you had a DOI for this repository?

Kind regards, @t-pollington

**Comment by rebeccanash** [comment]
Hi @t-pollington,

The DOI is: https://doi.org/10.5281/zenodo.3333653

Best, @rebeccanash

**Comment by t-pollington** [comment]
Thanks @rebeccanash, I'll add that to my manuscript and add it here as a pull request.
